Sprint 2
AlexPanich/middle.messenger.praktikum.yandex pull request #13
Opened 2021-06-12 18:27 UTC by AlexPanich

2021-06-13 23:49 UTC, avdoshenkov requested changes
Всё реализовано круто! По заданию пункты учтены, компоненты и страницы разбиты логично, по коду удобно перемещаться, структура понятна. 

Два момента хотел только отметить. Первый — перепроверь, пожалуйста, типы полей для ввода email и номера телефона, сейчас везде `type="text"`, а это не совсем хорошо (например, на мобильном устройстве клавиатура может меняться в зависимости от типа так, чтобы пользователю удобно было номер телефона набрать, либо адрес почты ввести).

Во-вторых, заметил пару косяков с вёрсткой, когда высота окна баузера не очень большая.

Первый на экране регистрации:
<img width="1440" alt="Registration screen" src="https://user-images.githubusercontent.com/26881016/121825361-0173fe00-ccc3-11eb-8669-2c842dae8233.png">
Как вариант, можно поля на две колонки разбить. Либо просто добавить `overflow: auto;` у контейнера, чтобы появилась возможность скроллить форму.

Второй на экране редактирования данных пользователя:
<img width="1440" alt="Profile edit screen" src="https://user-images.githubusercontent.com/26881016/121825420-53b51f00-ccc3-11eb-9fba-d447d20d7b30.png">

Тут блоку с аватаркой надо задать минимальную высоту, чтобы его не сжимало таким образом.


А так всё отлично, молодец!

2021-06-13 23:49 UTC, avdoshenkov commented on src/framework/validator.ts
> +    email: /^[\w-\.]+@([\w-]+\.)+[\w-]{2,4}$/,
Как альтернативный вариант валидации `email`, можно просто задать полю ввода тип `email`, и если у формы не стоит атрибут `novalidate`, то браузер сам проверит почтовый адрес на валидность.

2021-06-13 23:49 UTC, avdoshenkov commented on src/pages/edit-profile/edit-profile.ts
> +      errorMessage: "Некоректное телефон",
С точки зрения кода всё верно, в самом тексте ошибки в нескольких местах только небольшие грамматические неточности есть

2021-06-13 23:49 UTC, avdoshenkov commented on src/pages/regisration/registration.ts
> +      errorMessage: "Некоректное телефон",
Тут также стоит проверить сам текст ошибок

2021-06-13 23:49 UTC, avdoshenkov commented on src/framework/event-bus.ts
> +      (listener) => listener !== callback
Проверка правильная, но нужно быть с ней аккуратным, поскольку функции будут считаться равными, если это, фактически, ссылки на одну и ту же функцию:

```
const a = b = () => { console.log('a, b') }
a === b // true
const c = () => { console.log('a, b') }
a === c // false
```

Таким образом, например, если в `on` и `off`, например, будет передаваться вот такая функция `on(calcSomething.bind(this))`, то при каждом вызове метода `on` в массив `listeners` будет записываться новая функция, посколько именно новую функцию с новым контекстом возвращает `bind`. Это просто стоит иметь в виду

2021-06-14 07:50 UTC, AlexPanich commented on src/components/editInfo/editInfo.hbs
>                name={{name}}
готово

2021-06-14 07:51 UTC, AlexPanich commented on src/components/form/form.hbs
> +        <input
готово

2021-06-14 07:55 UTC, AlexPanich commented on src/components/message/messageElem.hbs
> +      <div class="message__time">{{time}}</div>
готово

2021-06-14 07:55 UTC, AlexPanich commented on src/components/message/messageElem.hbs
> +      <div class="message__time">{{time}}</div>
готово

2021-06-14 08:09 UTC, AlexPanich commented on src/framework/validator.ts
> +    phone: /^\+?(\d{1,3})?[- .]?\(?(?:\d{2,3})\)?[- .]?\d\d\d[- .]?\d\d\d\d$/,
готово, подправил regexp

2021-06-14 08:11 UTC, AlexPanich commented on src/framework/validator.ts
> +    email: /^[\w-\.]+@([\w-]+\.)+[\w-]{2,4}$/,
готово

2021-06-14 08:14 UTC, AlexPanich commented on src/pages/edit-profile/edit-profile.ts
> +      errorMessage: "Некоректное телефон",
готово

2021-06-14 08:14 UTC, AlexPanich commented on src/pages/regisration/registration.ts
> +      errorMessage: "Некоректное телефон",
готово

2021-06-14 08:18 UTC, AlexPanich commented on src/framework/event-bus.ts
> +      (listener) => listener !== callback
да это так, но я всегда сохраняю ссылку на функцию. 
cont event = 'someEvent'
const listener = calcSomething.bind(this);
on(event, listener)
off(event, listener)

2021-06-14 08:18 UTC, AlexPanich commented on src/framework/utils.ts
> +    (acc: ChildrenProps, _, index: number) => {
готово

2021-06-14 08:22 UTC, AlexPanich commented on src/framework/fetch.ts
> +  return Object.entries(data)
готово

2021-06-14 08:23 UTC, AlexPanich commented on src/components/profileContent/profileContent.ts
> +import Aratar from "../avatar/avatar";
готово

2021-06-14 08:23 UTC, AlexPanich commented on src/components/message/messageElem.hbs
> +      <div class="message__time">{{time}}</div>
готово

2021-06-14 08:59 UTC, AlexPanich commented on src/framework/block.ts
> +    target: Element;
готово

2021-06-14 11:06 UTC, avdoshenkov approved these changes
Отлично, хорошо поработал 👍

2021-06-14 19:55 UTC, merged