Sprint 1
AlexPanich/middle.messenger.praktikum.yandex pull request #4
Opened 2021-06-05 02:42 UTC by AlexPanich

2021-06-06 10:41 UTC, nickchamel commented on package.json
> +    "start": "parcel build static/*.html --out-dir dist --no-source-maps && node server.js"
--out-dir по умолчанию dist - можно не писать

2021-06-06 12:26 UTC, nickchamel requested changes
Привет! В целом все очень аккуратно и красиво, отличная работа! Есть несколько мелких моментов и несколько не мелких, описал о них в комментариях к пулл-реквесту...
Плюс по самим заданиям есть пара не выполненных. Убедись, пожалуйста, что:
1. Ссылка на figma работает в README.md
2. Автодеплой на netlify настроен из ветки deploy

2021-06-06 12:39 UTC, nickchamel commented on src/pages/change-chat/change-chat.js
> +app.innerHTML = template(data);
Из-за hbs precompile у тебя в переменной template лежит не шаблон, а функция. А по коду читается как буд-то ты вызываешь шаблон. Для лучшей читаемости кода будет лучше называть это как функцию, например, templateFn или compileTemplate как в доке hbs

2021-06-06 16:09 UTC, AlexPanich commented on package.json
> +    "start": "parcel build static/*.html --out-dir dist --no-source-maps && node server.js"
готово

2021-06-06 16:09 UTC, AlexPanich commented on server.js
> +});
готово

2021-06-06 16:11 UTC, AlexPanich commented on src/components/contact/contact.hbs
> +  </div>
готово, сделал хэлпер для этого

2021-06-06 16:11 UTC, AlexPanich commented on src/components/contact/contact.js
> +Handlebars.registerPartial({ avatar });
Готово. Изменения во всех компонентах и страницах

2021-06-06 16:13 UTC, AlexPanich commented on src/components/messager/messager.js
> +import Handlebars from "handlebars/dist/handlebars.runtime";
готово, везде упорядочил. Экспорты вобще убрал так как мы регистрируем модуль, то особо экспортировать ничего не нужно

2021-06-06 16:13 UTC, AlexPanich commented on src/components/tab/tab.hbs
> +    <a class="tab__link" href={{link}}>{{#if avatar}}
готово

2021-06-06 16:13 UTC, AlexPanich commented on src/layouts/base/base.hbs
> +</main>
готово

2021-06-06 16:13 UTC, AlexPanich commented on src/pages/change-password/change-password-data.js
> +    center: false,
готово. для страниц настроики создал свой layout

2021-06-06 16:59 UTC, AlexPanich commented on src/pages/change-password/change-password.js
> +});
Готово

2021-06-06 17:02 UTC, AlexPanich commented
Убедись, пожалуйста, что:

Ссылка на figma работает в README.md
Автодеплой на netlify настроен из ветки deploy
Проверил, все работает

2021-06-06 17:24 UTC, AlexPanich commented
Добавил ссылки на Figma и Netlify в README.md в ветке main

2021-06-06 18:00 UTC, AlexPanich reviewed
все пункты поправил

2021-06-07 09:52 UTC, AlexPanich commented on src/pages/change-password/change-password.js
>  editInfoForm.addEventListener("submit", (event) => {
ок. поправлю сразу!

2021-06-07 10:12 UTC, merged